### PR TITLE
Entrez updates

### PR DESCRIPTION
**Pull request by ahwagner**
Entrez auto-updates for #23 .

### CODE REVIEW

**Comment by ahwagner** [comment]
For anyone reviewing this:

```shell
cd $PROJECT_ROOT/lib/genome/updaters/
python3 get_entrez.py

cd $PROJECT_ROOT
rake dgidb:import:entrez[lib/genome/updaters/data/entrez_genes.tsv,true]
```

**Comment by obigriffith** [comment]
So far everything looks as it should except the "inter-gene interactions" aka related genes are not being imported from Entrez. Compare the source summary for Entrez in this version vs public site. I don't recall if this was handled by a separate import or not but in any case it should be done at the same time. 

screenshot 2015-08-25 14 04 23
screenshot 2015-08-25 14 05 34

**Comment by acoffman** [comment]
I believe there is a separate importer for Gene-Gene interactions under `lib/genome/importers/entrez/entrez_gene_pathway_importer.rb`

**Comment by obigriffith** [comment]
What do you guys think?  Maybe this should just be incorporated into a single automated import/update for Entrez?

**Comment by ahwagner** [comment]
@obigriffith I think it should be. The short-term solution is to just hard-code the update cron to run the `EntrezGenePathwayImporter` immediately after the `EntrezGenesImporter` when Entrez is updated.

For now, Entrez inter-gene interactions can be updated as follows:

```shell
cd $PROJECT_ROOT/lib/genome/updaters/
rm data/version
python3 get_entrez.py

cd $PROJECT_ROOT
rake dgidb:import:entrez_pathway[lib/genome/updaters/data/interactions.human]
rake dgidb:normalize:populate_source_counters
```

image

**Pull request merged**
