### PR TITLE
Initial pubchem updater

### PR DESCRIPTION
**Pull request by acoffman**
@ahwagner  had asked me to take a stab at bringing the old PubChem importer over from the Genome repo. Here's a first draft - I'm chatting with him now about it.

### CODE REVIEW

**Comment by acoffman** [comment]
This works via the same general algorithm as the [perl version](https://github.com/genome/genome/blob/master/lib/perl/Genome/DruggableGene/Command/Import/Pubchem.pm):

* Delete existing PubChem data in the DGIdb database
* Download the gzipped PubChem synonyms file
* Iterate the PubChem file, looking for drugs for which we have interactions that match something in PubChem
* For matches, create a new DrugClaim with the primary PubChem compound name and import all the remaining PubChem names for the same compound as synonyms
* Import the PubChem CID as an alias for the DrugClaim

It can be invoked with `rake dgidb:import:pubchem` and takes several minutes to run to completion (including the download) as the file is > 100,000,000 lines.

**Comment by ahwagner** [comment]
The problem may be [here](https://github.com/genome/dgi-db/blob/master/lib/genome/groupers/drug_grouper.rb#L23-L27). If your new alias is mixed case, it wouldn't match the regex, and the drug grouper won't know what to match to.

**Comment by ahwagner** [comment]
Hey @acoffman, is 3eed6c3 the most recent commit to this branch?

**Comment by acoffman** [comment]
@ahwagner Yup! That is a version of the importer that resulted in the numbers I sent you on Friday.

**Comment by ahwagner** [comment]
Great. Just checking. +1

> On Aug 31, 2015, at 10:15 AM, Adam Coffman <notifications@github.com> wrote:
> 
> @ahwagner <https://github.com/ahwagner> Yup! That is a version of the importer that resulted in the numbers I sent you on Friday.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/genome/dgi-db/pull/41#issuecomment-136402813>.
> 



____
This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Pull request merged**
