### PR TITLE
Add Guide To Pharmacology D-G Interaction Source

### PR DESCRIPTION
**Pull request by ahwagner**
Add guide_to_pharmacology interactions from http://www.guidetopharmacology.org/about.jsp. Update schema to add default values for gene-gene interaction counts (minor fix).

Data file for import may be found here: https://www.dropbox.com/s/7t0z8iv8zbjgoss/gtp_interactions.4_mar_2015.expected_cols.tsv?dl=0

rake command:
rake dgidb:import:guide_to_pharmacology_interactions[path_to_gtp_interactions_tsv,true]

### CODE REVIEW

**Comment by malachig** [comment]
Alex.  This is great.  Has @acoffman had a chance to look this over?

In the past we have only allowed `human` interactions.  For consistency, I think we should stick with the convention here.  To make updates easier in the future maybe skipping non-human entries could be part of the importer.  Maybe it already is and I just missed it.

**Comment by ahwagner** [comment]
As far as I know, @acoffman hasn't seen it yet. 

I agree with this convention. I skipped any `non-human` interactions at line 52 of guide_to_pharmacology_interactions_row.rb.

**Comment by malachig** [comment]
Ah, sorry read right over that. Sounds good.  Assuming everything is order we should push this out to the public site as soon as practical.  But lets give a @acoffman a chance to review.  @nspies13 could you give it a quick review as well when you have a minute?

**Comment by acoffman** [comment]
I'll take a look at this today. Awesome!

**Comment by nspies13** [comment]
I will as well.

**Comment by ahwagner** [comment]
@acoffman, I've updated the file to be imported so it now includes 13582 of the 13597 original records, an improvement of about 6% over the originally shared file.

The new file for import may be found online:
https://www.dropbox.com/s/6ez7i1c9mgvppm8/gtp_interactions.4_mar_2015.tsv?dl=0

**Comment by acoffman** [comment]
@ahwagner Great, I'll check it out!

**Comment by ahwagner** [comment]
@acoffman - you'll need to re-import after the new edits in my latest commit, as I slightly modified the importer to use different fields as the primary identifier for the drugs and genes. Let me know if you have any questions!

**Comment by nspies13** [comment]
This pull on my laptop works as intended! Looks great @ahwagner!

**Comment by malachig** [comment]
Thanks for kicking the tires @nspies13 !

**Comment by nspies13** [comment]
I was exploring yesterday, but couldn't find how to give @ahwagner write access to DGIdb. Can someone more familiar with Github do this? Sorry.

**Comment by acoffman** [comment]
@nspies13 invite sent to @ahwagner!

**Pull request merged**
